version: '3'
services:
  front:
    build: vue/.
    volumes:
      - ./vue:/vue
    ports:
      - "9002:8080"

  back:
    build: node/.
    ports:
      - "80:80"
    volumes:
      - ./node:/node/
    depends_on:
      - mongo

  mongo: # this name is used on url of mongodb!
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
