FROM node:lts-alpine as build-stage
WORKDIR /vue
COPY package*.json /vue/
RUN npm install
COPY . /vue/
RUN npm run build

FROM nginx as production-stage
RUN mkdir /vue
COPY --from=build-stage /vue/dist /var/www/html
#RUN cd /vue && ls && cd ..
COPY nginx.conf /etc/nginx/nginx.conf
